"""
Alembic environment. Three ways this runs, all pointed at the same code:

  1. CLI:       `alembic upgrade head`, `alembic revision --autogenerate -m ...`
                -> connects to settings.database_url (DATABASE_URL in .env).
  2. App start: app/migrations.py hands in an already-open connection via
                config.attributes["connection"], so startup migrates the very
                engine the app is about to use (also what the smoke tests hit).
  3. Offline:   `alembic upgrade head --sql` prints the SQL instead of running it.

render_as_batch=True lets autogenerated migrations use batch_alter_table,
which is what makes ALTER COLUMN / DROP COLUMN work on SQLite (dev) as well
as Postgres (prod). See docs/MIGRATIONS.md.
"""
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.config import settings
from app.database import Base
import app.models  # noqa: F401  (registers every table on Base.metadata)

config = context.config
if config.config_file_name is not None and config.attributes.get("configure_logger", True):
    # disable_existing_loggers=False: don't silence the app's own loggers
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata


def _url() -> str:
    return config.get_main_option("sqlalchemy.url") or settings.database_url


def _configure(**kwargs):
    context.configure(target_metadata=target_metadata, render_as_batch=True, compare_type=True, **kwargs)


def run_migrations_offline() -> None:
    _configure(url=_url(), literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connection = config.attributes.get("connection")
    if connection is not None:
        _configure(connection=connection)
        with context.begin_transaction():
            context.run_migrations()
        return

    section = config.get_section(config.config_ini_section) or {}
    section["sqlalchemy.url"] = _url()
    engine = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)
    with engine.connect() as conn:
        _configure(connection=conn)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
